# Numpy tutorial
numpy的基本使用方法

In [1]:
import numpy as np

## 创建

In [2]:
np.zeros((3,2))
# np.zeros_like()

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [3]:
np.zeros((3,2)) + 1

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [4]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [5]:
np.random.randn(2,3)

array([[-1.04935711,  0.43330788, -0.64233615],
       [-0.17700479, -1.16425304, -1.33869813]])

In [6]:
np.random.randint(low=1, high=10, size=(2,3))

array([[7, 7, 6],
       [9, 3, 2]])

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 切片访问

In [8]:
a = np.random.randint(low=1, high=10, size=(2,3))
a

array([[4, 9, 2],
       [5, 6, 8]])

In [9]:
a[1][1]

6

In [10]:
a[1,1]

6

In [11]:
a[:,2:]

array([[2],
       [8]])

In [12]:
a[[0,1]]

array([[4, 9, 2],
       [5, 6, 8]])

In [13]:
# 学着点
a[:,[0,1]]

array([[4, 9],
       [5, 6]])

## 维度变换

In [14]:
base = np.arange(1,7)
base

array([1, 2, 3, 4, 5, 6])

### reshpe

In [15]:
base.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [16]:
# reshpe
b_1 = np.reshape(base,(3,2))
b_1

array([[1, 2],
       [3, 4],
       [5, 6]])

### squeeze&unsqueeze
squeeze可以理解为消除大小为1的维度

In [17]:
temp = b_1.reshape(1,6)
print(temp)

[[1 2 3 4 5 6]]


In [18]:
temp.squeeze(axis=0)

array([1, 2, 3, 4, 5, 6])

In [19]:
# temp.squeeze(axis=0).unsqueeze()

### concatenate/stack/dstack

一般约定俗成：
- **axis=0 对行进行扩展**
- **axis=0 对列进行扩展**

In [20]:
t_1 = np.zeros((2,3))+1
t_2 = np.zeros((2,3))+2
t_1, t_2

(array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[2., 2., 2.],
        [2., 2., 2.]]))

In [21]:
np.concatenate((t_1, t_2), axis=0)

array([[1., 1., 1.],
       [1., 1., 1.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [22]:
np.concatenate((t_1, t_2), axis=1)

array([[1., 1., 1., 2., 2., 2.],
       [1., 1., 1., 2., 2., 2.]])

In [23]:
arrays = [np.random.randn(3, 4) for _ in range(10)]
print(np.stack(arrays, axis=0).shape)
print(np.stack(arrays, axis=1).shape)
print(np.stack(arrays, axis=2).shape)

(10, 3, 4)
(3, 10, 4)
(3, 4, 10)


In [24]:
ndarrays = np.arange(6).reshape(2,3,1)
ndarrays

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [25]:
# 按照第 axis 个维度进行 堆叠
np.stack(ndarrays, axis=0)

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [26]:
np.stack(ndarrays, axis=1)

array([[[0],
        [3]],

       [[1],
        [4]],

       [[2],
        [5]]])

In [27]:
np.stack(ndarrays, axis=2)

array([[[0, 3]],

       [[1, 4]],

       [[2, 5]]])

In [28]:
np.dstack((t_1, t_2))

array([[[1., 2.],
        [1., 2.],
        [1., 2.]],

       [[1., 2.],
        [1., 2.],
        [1., 2.]]])

## broadcasting机制
对于两个不同的维度的ndarray，broadcasting只能沿着行的方向进行（第一行，第二行，，，等等）

## 其他常用函数操作

In [29]:
# 1.numpy乘法运算中"*"是数组元素逐个计算
# 2.numpy乘法运算中dot是按照矩阵乘法的规则来运算的
# np.random.choice?
# np.argmax? #  选出数组中最大值对应的索引