# 训练过程中涉及到的一些函数

In [1]:
import torch
from torch.nn.utils.rnn import pack_padded_sequence

In [6]:
criterion = torch.nn.CrossEntropyLoss()

In [3]:
y=[
    [1,2,3,4],
    [5,6,7,0]
]
y_hat=[
    [1,2,3,3],
    [5,6,7,0]
]
y=torch.Tensor(y)
y_hat=torch.Tensor(y_hat)
y, y_hat

(tensor([[1., 2., 3., 4.],
         [5., 6., 7., 0.]]),
 tensor([[1., 2., 3., 3.],
         [5., 6., 7., 0.]]))

In [4]:
y=pack_padded_sequence(y,lengths=[4,3],batch_first=True).data
y_hat=pack_padded_sequence(y_hat,lengths=[4,3],batch_first=True).data
y, y_hat

(tensor([1., 5., 2., 6., 3., 7., 4.]), tensor([1., 5., 2., 6., 3., 7., 3.]))

In [5]:
criterion(y,y_hat)

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [ ]:
import torch.nn.functional as F

In [ ]:
input = torch.randn(3, 5, requires_grad=True)
target = torch.randint(5, (3,), dtype=torch.int64)
input, target

In [ ]:
loss = F.cross_entropy(input, target)
loss.item()
# loss.backward()

In [ ]:
a = torch.zeros((2,3))
a

In [ ]:
b = torch.randn((2))
b = b.view(2,1)
b

In [ ]:
print('val:\nEpoch: {:}\tLoss: {:.3f}\tBLEU4: {:.3f}'.format(1, 1, 1))
print('\n')
